services:
    pgdatabase:
        image: postgres:14
        env_file:
            - .env
        volumes:
            - "./financial_postgres_data:/var/lib/postgresql/data:rw"
        ports:
            - "5432:5432"
        networks:
            - simple_elt

    pgadmin:
        image: dpage/pgadmin4
        env_file:
            - .env
        ports:
            - "5050:80"
        depends_on:
            - pgdatabase
        networks:
            - simple_elt

networks:
    simple_elt:
        external: true